### PR TITLE
Filled out ranking use case, and modified account user to add score a…

### PR DESCRIPTION
**Pull request by mitchellpotter**
…ttribute to be ranked among other users.

Changes to be looked at:
- AccountUser changes, implemented interface Comparable to allow for ranking
- AccountUser changes, added score attribute and getter method
- Rank use case follows clean architecture? Not totally sure if I fully succeeded in understanding it.

### CODE REVIEW

**Comment by INCREDIJOSH** [comment]
Hey man. You need to resolve the conflicts before they can be approved.

**Comment by mitchellpotter** [comment]
> Hey man. You need to resolve the conflicts before they can be approved.

For sure, I checked it over the conflict came from my change to Account now implementing comparable.

**Comment by mitchellpotter** [comment]
Remaining conflict caused by Java failing to build, I'll take a look at it again

**Review by Moe-Reda — DISMISSED** [review]
Looks good to me.

**Comment by mitchellpotter** [comment]
Fixed conflict, Git was not pushing added interfaces along with the code

**Review by INCREDIJOSH — APPROVED** [review]
Very nice.

**Review by emjennett — APPROVED** [review]

**Review by emjennett — APPROVED** [review]
Looks good! It follows clean architecture and compares accounts successfully.

**Review by LJCar — APPROVED** [review]
had a look at the code before it was pushed. It works!

**Pull request merged**
