### PR TITLE
Profile implementation 

### PR DESCRIPTION
**Pull request by SheldonDacon**
fixed a bug which caused an error when you initially log in

### CODE REVIEW

**Review by Moe-Reda — DISMISSED** [review]

**Review by INCREDIJOSH — DISMISSED** [review]
Very good.

**Review by INCREDIJOSH — APPROVED** [review]
Nice fix

**Review by emjennett — APPROVED** [review]
love all the new features! amazing

**Review by mitchellpotter — APPROVED** [review]
looks great, awesome

**Pull request merged**
