### PR TITLE
Data Storage

### LINKED ISSUE #8: Database and other related tasks
create classes for the manipulation of a database.

### PR DESCRIPTION
**Pull request by INCREDIJOSH**
Changed classes to implement serializable.
Added basic design for reading and writing from data files.

### CODE REVIEW

**Review by Moe-Reda — DISMISSED** [review]

**Review by emjennett — DISMISSED** [review]
Looks good!

**Review by LJCar — APPROVED** [review]
Lets try this

**Review by LJCar — DISMISSED** [review]
Lets try it

**Review by emjennett — APPROVED** [review]

**Review by emjennett — APPROVED** [review]

**Review by LJCar — APPROVED** [review]
try this number #2

**Review by SheldonDacon — APPROVED** [review]

**Pull request merged**
