### PR TITLE
added profile tab

### PR DESCRIPTION
**Pull request by SheldonDacon**

### CODE REVIEW

**Review by emjennett — DISMISSED** [review]
it looks so good!!

**Review by INCREDIJOSH — DISMISSED** [review]
good

**Review by mitchellpotter — DISMISSED** [review]
looking good

**Review by emjennett — DISMISSED** [review]

**Review by LJCar — CHANGES_REQUESTED** [review]
I have overlooked the logic of going into another use case package. You should not be adding to login_user instead on the tab screen take the information that log in user gives which is the username and create your own response model for your use case to be saved to a csv file to add the features you want. I would recommend creating a new entity called profile. Adding an input boundary would then allow you to take user input and create a profile page layout feature.

**Pull request closed without merging**
