### PR TITLE
3 view restaurants and dish informations

### PR DESCRIPTION
**Pull request by Moe-Reda**
Let me know if you are okay with this version, and when the review and profile related classes are ready to be used.

### CODE REVIEW

**Review by INCREDIJOSH — DISMISSED** [review]

**Review by LJCar — CHANGES_REQUESTED** [review]
Yeah it looks great the main page looks clean and I tested a few things on the search bar!

For your new implementation the screens for login and create user screens need to be separated. It should be clear that yes UI is free for anyone to update and change to be more efficient but you should ask or communicate with the person whose code you would like to change outside of UI because the create account success message doesn't work anymore from what I see you changed my code. I know how to change it to work tho.  

This can be something we can edit and push for the final submission.

**Review by LJCar — DISMISSED** [review]

**Review by mitchellpotter — DISMISSED** [review]
looks good

**Review by mitchellpotter — APPROVED** [review]
looks great!

**Review by INCREDIJOSH — APPROVED** [review]
good good

**Review by SheldonDacon — COMMENTED** [review]
The program doesn't show anything when I try to login, is anyone else having this issue? I believe that It's caused by the UI not updating the main page after it is finished loading all of the initial screens, I should be a rather simple fix by making sure that the UI implementation uses the switch function on the main page, remember that you can only use the switch function on JPanels that have the Cardlayout

**Review by LJCar — APPROVED** [review]
I originally approved but changes were made.

**Pull request merged**
