### PR TITLE
Use Case: Create User: 

### LINKED ISSUE #4: Account Creation
The account creation for casual users for storing their information.

### PR DESCRIPTION
**Pull request by LJCar**
Completed code with its own gateway and data-storing system. This Commit does not include UI.

### CODE REVIEW

**Review by Moe-Reda — COMMENTED** [review]
A bit confused about the use of UserFile when we have DataAccessStorage. Also is findAccountUser()' s purpose to find users or check if a username is already being used ?

**Review by INCREDIJOSH — DISMISSED** [review]
Looks good.

**Review by emjennett — COMMENTED** [review]
Looks good to me! All the dependencies are correct and the data input/output handling looks thorough.

**Review by emjennett — DISMISSED** [review]

**Review by SheldonDacon — DISMISSED** [review]
It looks good. Great use of the interface segregation principle in the create User Gateway interface. I think as a general rule that it's a good idea have only a couple of methods in our interfaces so that users don't end up depending on things that they don't need.

**Review by PhiliDips — DISMISSED** [review]
Looks solid to me.

**Review by mitchellpotter — APPROVED** [review]
Looks good, simple changes.

**Review by SheldonDacon — APPROVED** [review]

**Review by emjennett — APPROVED** [review]

**Pull request merged**
