### PR TITLE
Revert "Added types to Account entities, added upload restaurant use case and more UI stuff"

### PR DESCRIPTION
**Pull request by INCREDIJOSH**
Reverts CSC207-2022F-UofT/course-project-digitaldiningdivas#40

### CODE REVIEW

**Review by LJCar — APPROVED** [review]
we go back in time

**Review by mitchellpotter — APPROVED** [review]
Revert should work

**Review by LJCar — APPROVED** [review]
back again

**Review by mitchellpotter — APPROVED** [review]
Looks good, revert should work

**Pull request merged**
