### PR TITLE
Further developed the Restaurant use case; added simple GUI in Main.

### LINKED ISSUE #12: Restaurant Controllers and Use Cases
Attempting to implement the interactors and such for the Restaurant user story

### PR DESCRIPTION
**Pull request by emjennett**

### CODE REVIEW

**Review by mitchellpotter — DISMISSED** [review]
- everything looks good, UI implementation works and is functional
- edits seem good nothing large removed or changed
- Overall looks good, simple fixes seem to have been made and UI works great

**Review by INCREDIJOSH — DISMISSED** [review]
Looks good.

**Review by Moe-Reda — CHANGES_REQUESTED** [review]
Why did we delete Menu from the Restaurant class ? I need it there for my Use case.
Also, is the restaurant presenter there to display restaurants, because it is already done by the SearchRestaurant use case and presenter.

**Comment by emjennett** [comment]
> Why did we delete Menu from the Restaurant class ? I need it there for my Use case. Also, is the restaurant presenter there to display restaurants, because it is already done by the SearchRestaurant use case and presenter.
Hello hello, I deleted the Menu class because 1) I mistakenly didn't see that you were using the menu from the Restaurant class and 2) I realized that a Restaurant doesn't necessarily have menus. When initializing a Restaurant to begin with (ex: an owner creates a Restaurant to add menus to), it would be an empty restaurant to which you can add menus on. I added the menu parameter again but I set it to null. Hopefully that still works in your case? Lmk. Also, I'm currently focusing on how a restaurant owner can initially create a restaurant with menus, which I believe is a separate use case from searching and viewing other restaurants/dishes etc. I changed the "RestaurantPresenter" class to "RestaurantUploadPresenter". I can also change the other Restaurant related classes so that they're named more specifically. Lmk if that helps or if you have a different idea.

**Review by Moe-Reda — DISMISSED** [review]
Code looks good. Thank you for the changes.

**Review by INCREDIJOSH — DISMISSED** [review]
good

**Comment by SheldonDacon** [comment]
looks good

**Review by SheldonDacon — DISMISSED** [review]

**Review by LJCar — DISMISSED** [review]
A great working UI idea for the project. It will be implemented throughout the code for use cases.

**Review by mitchellpotter — DISMISSED** [review]
Looks good, only very simple changes made, solid.

**Review by LJCar — DISMISSED** [review]
} this is what you had to add

**Review by SheldonDacon — APPROVED** [review]
looks good

**Review by PhiliDips — APPROVED** [review]

**Review by LJCar — APPROVED** [review]
}

**Review by PhiliDips — COMMENTED** [review]
Looks lovely to me.

**Review by mitchellpotter — APPROVED** [review]
Simple changes }

**Pull request merged**
