### PR TITLE
Made functional Dish menu with UI

### PR DESCRIPTION
**Pull request by mitchellpotter**
Made Beginning of Dish Database
Worked on DishMenu Use Case

### CODE REVIEW

**Review by INCREDIJOSH — DISMISSED** [review]
Beautiful.

**Review by INCREDIJOSH — DISMISSED** [review]
That's good.

**Review by INCREDIJOSH — APPROVED** [review]
Thumbs up

**Review by emjennett — APPROVED** [review]
Everything looks great and functional! nice csv file yummy

**Review by SheldonDacon — APPROVED** [review]
looks good

**Pull request closed without merging**
